### ISSUE TITLE
Create Design Docs

### ISSUE THREAD

**Issue by acapela000** [areugoh/proto#119]
> ⚠ **Warning**: before working on this US we need to fill the Unclear points if any and the Estimation section

## Overview

In this User Story we need to create the design docs with description of the technology we are going to use in detail, the different components and main sections of the UI.
This Document will be under review through all of the process of the deployment. 
In order to successfully deliver this US we will have some dependency tasks described in the Task section.

## Tasks

- [x] Clone https://github.com/areugoh/proto
- [x] Install Bun https://bun.sh/docs/installation
- [x] cd scripts/doc-registry
- [ ] Switch to branch to work on
- [ ] Install dependencies
- [ ] Get familiar with docs
- [ ] Start to write the design in the folder `/design/short-url` and `/design/short-url/ui`
    - [ ] Create `index.md` file in `/design/short-url`
    - [ ] Create `index.md` file in `/design/short-url/ui`

The Documentation uses [markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet). As header metadata we need to specify at least the title. you have [here](https://starlight.astro.build/guides/pages/) a list of metadata that you can add.
```markdown
---
title: Frontend
description: Short URL UI
---
 ```

## Unclear Points

1. Why need to install proto
    Proto is the repository where we store all of the documentation of our organisation, there are 2 main sections in proto repository `protobuf definitions` where we describe the structure of our data and [bff gateway](https://bff-patterns.com/) which we are going to use in [grpc](https://grpc.io/) projects (in /proto folder). In our Shorten URL we are NOT going to use grpc. And our `doc registry` where we have all our documentation. the documentation uses [Astro](https://starlight.astro.build/) as a static frontend (in /scripts/doc-registry).
2. Why need to use `bun` instead of others
    Bun is a faster alternative for npm and pnpm. In order to lower the speed of the pipelines and make the ci/cd faster we decided to go with **bun**, Looks like the community adopted bun pretty fast and since npm is getting obsolete is some areas, I think is a good time to try bun in not a critical project.
3. Which brach should I switch to to work on
    You can choose the branch name you want, I recommend you to use the User Story ID and the short description as follow: `US-ID/Short-description` eg: `1/short-url-ui-docs`. A better way to create a new branch is to click on the `convert to issue` in this US, that way you will need to select a repository where this US will be created and after that you will be able to create a branch:

![Image](https://github.com/areugoh/proto/assets/4450555/b2a0e91a-6229-44d9-9300-9457259db709)

![Image](https://github.com/areugoh/proto/assets/4450555/0c647d7b-e096-438c-948f-ff0e48569e2a)

4. Where can I install the dependencies
    When you download bun in your computer and cd into scripts/doc-registry you can run `bun install`
5. ''Get familiar with docs'' -> Which docs and where can I find it
    The docs are in `scripts/doc-registry` folder. run `bun run dev` to start the localhost server and navigate to [this folder](https://github.com/areugoh/proto/tree/main/scripts/doc-registry/src/content/docs/design) to read them

## Estimations

> Days / Effort => eg. 5 / 0.5 = 10

### @acapela000 
- xx / xx = `xx`

### @jorgechato 
- xx / xx = `xx`
